version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hatamiarash7"
    reviewers:
      - "hatamiarash7"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hatamiarash7"
    reviewers:
      - "hatamiarash7"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "semver"
      - dependency-name: "crates-io"
    rebase-strategy: "disabled"
