image: node:latest

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

variables:
  GIT_USER: "hatamiarash7"
  CURRENT_BRANCH: "master"
  USE_SSH: "true"

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - deploy

before_script:
  - yarn config set cache-folder .yarn
  - yarn install

Build:
  stage: build
  script:
    - yarn build

Deploy:
  stage: deploy
  script:
    - git config --global user.name "${GH_NAME}"
    - git config --global user.email "${GH_EMAIL}"
    - mkdir -p ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - echo "${GH_PAGES_DEPLOY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tHostName github.com\n\tIdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
    - yarn run deploy

dependency_scanning:
  stage: .pre
  variables:
    DS_REMEDIATE: "false"
  artifacts:
    expire_in: 1 week
    reports:
      dependency_scanning: gl-dependency-scanning-report.json

license_scanning:
  stage: .pre
  variables:
    CI_DEBUG_TRACE: "true"
    ASDF_NODEJS_VERSION: 12
  artifacts:
    expire_in: 1 week
    reports:
      license_scanning: gl-license-scanning-report.json

dast:
  stage: .pre
  variables:
    DAST_WEBSITE: https://nikasproject.ir
    DAST_DEBUG: "true"
    DAST_HTML_REPORT: report.html
    DAST_MARKDOWN_REPORT: report.md
    DAST_XML_REPORT: report.xml
  artifacts:
    expire_in: 1 week
    paths:
      - $DAST_HTML_REPORT
      - $DAST_MARKDOWN_REPORT
      - $DAST_XML_REPORT
    reports:
      dast: gl-dast-report.json

spotbugs-sast:
  stage: .pre
  variables:
    FAIL_NEVER: 1
  artifacts:
    reports:
      sast: gl-sast-report.json
